### ISSUE TITLE
"npm install" fails (on repeated runs) when using current versions of npm

### ISSUE THREAD

**Issue by 4ch1m** [Esshahn/spritemate#200]
Hey there,

the current state of the repo seems to have issues with the dependency management.

I'm not sure what exactly is the problem. But it can be reproduced pretty easy.

* simply check out the repo:
  ```
  git clone git@github.com:Esshahn/spritemate.git && cd spritemate
  ```

* use a Node-container to run `npm install`:
  ```
  docker \
    run \
    -it \
    --rm \
    -v "$(pwd)":/usr/src/app \
    -w /usr/src/app \
    node:19 npm install
  ```
  which seems to work fine at first (altering the package-lock.json) -->
  ```
   npm WARN old lockfile 
   npm WARN old lockfile The package-lock.json file was created with an old version of npm,
   npm WARN old lockfile so supplemental metadata must be fetched from the registry.
   npm WARN old lockfile 
   npm WARN old lockfile This is a one-time fix-up, please be patient...
   npm WARN old lockfile 
   npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
   npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
   npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
   npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
   npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
   npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
   npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
   
   added 798 packages, and audited 799 packages in 9s
   
   65 packages are looking for funding
     run `npm fund` for details
   
   36 vulnerabilities (2 low, 11 moderate, 20 high, 3 critical)
  ```

* but every subsequent call fails as follows:
  ```
  docker \
    run \
    -it \
    --rm \
    -v "$(pwd)":/usr/src/app \
    -w /usr/src/app \
    node:19 npm install
  ```
  -->
  ```
   npm WARN ERESOLVE overriding peer dependency
   npm WARN While resolving: css-loader@1.0.1
   npm WARN Found: webpack@5.12.2
   npm WARN node_modules/webpack
   npm WARN   dev webpack@"^5.8.0" from the root project
   npm WARN   7 more (html-webpack-plugin, mini-css-extract-plugin, ...)
   npm WARN 
   npm WARN Could not resolve dependency:
   npm WARN peer webpack@"^4.0.0" from css-loader@1.0.1
   npm WARN node_modules/css-loader
   npm WARN   css-loader@"^1.0.0" from webpack-jquery-ui@2.0.1
   npm WARN   node_modules/webpack-jquery-ui
   npm WARN 
   npm WARN Conflicting peer dependency: webpack@4.46.0
   npm WARN node_modules/webpack
   npm WARN   peer webpack@"^4.0.0" from css-loader@1.0.1
   npm WARN   node_modules/css-loader
   npm WARN     css-loader@"^1.0.0" from webpack-jquery-ui@2.0.1
   npm WARN     node_modules/webpack-jquery-ui
   npm notice 
   npm notice New minor version of npm available! 9.4.0 -> 9.5.0
   npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.0
   npm notice Run npm install -g npm@9.5.0 to update!
   npm notice 
   npm ERR! code ERESOLVE
   npm ERR! ERESOLVE could not resolve
   npm ERR! 
   npm ERR! While resolving: file-loader@1.1.11
   npm ERR! Found: webpack@5.12.2
   npm ERR! node_modules/webpack
   npm ERR!   dev webpack@"^5.8.0" from the root project
   npm ERR!   peer webpack@"^4.0.0 || ^5.0.0" from html-webpack-plugin@4.5.1
   npm ERR!   node_modules/html-webpack-plugin
   npm ERR!     dev html-webpack-plugin@"^4.5.0" from the root project
   npm ERR!   6 more (mini-css-extract-plugin, terser-webpack-plugin, ...)
   npm ERR! 
   npm ERR! Could not resolve dependency:
   npm ERR! peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from file-loader@1.1.11
   npm ERR! node_modules/file-loader
   npm ERR!   dev file-loader@"^1.1.11" from the root project
   npm ERR!   file-loader@"^1.1.11" from webpack-jquery-ui@2.0.1
   npm ERR!   node_modules/webpack-jquery-ui
   npm ERR!     webpack-jquery-ui@"^2.0.1" from the root project
   npm ERR! 
   npm ERR! Conflicting peer dependency: webpack@4.46.0
   npm ERR! node_modules/webpack
   npm ERR!   peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from file-loader@1.1.11
   npm ERR!   node_modules/file-loader
   npm ERR!     dev file-loader@"^1.1.11" from the root project
   npm ERR!     file-loader@"^1.1.11" from webpack-jquery-ui@2.0.1
   npm ERR!     node_modules/webpack-jquery-ui
   npm ERR!       webpack-jquery-ui@"^2.0.1" from the root project
   npm ERR! 
   npm ERR! Fix the upstream dependency conflict, or retry
   npm ERR! this command with --force or --legacy-peer-deps
   npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
  ```

*  this can be "fixed" by using `npm install --legacy-peer-deps` instead; **BUT** calling `npm run build` afterwards will fail with this:
  ```
  docker \
    run \
    -it \
    --rm \
    -v "$(pwd)":/usr/src/app \
    -w /usr/src/app \
    node:19 npm run build
  ```
  -->
  ```
   > spritemate@1.2.1 build
   > rm -rf dist && webpack --mode production
   
   Error: error:0308010C:digital envelope routines::unsupported
       at new Hash (node:internal/crypto/hash:71:19)
       at Object.createHash (node:crypto:140:10)
       at BulkUpdateDecorator.hashFactory (/usr/src/app/node_modules/webpack/lib/util/createHash.js:138:18)
       at BulkUpdateDecorator.update (/usr/src/app/node_modules/webpack/lib/util/createHash.js:44:50)
       at RawSource.updateHash (/usr/src/app/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:64:8)
       at NormalModule._initBuildHash (/usr/src/app/node_modules/webpack/lib/NormalModule.js:752:17)
       at handleParseResult (/usr/src/app/node_modules/webpack/lib/NormalModule.js:816:10)
       at /usr/src/app/node_modules/webpack/lib/NormalModule.js:907:4
       at processResult (/usr/src/app/node_modules/webpack/lib/NormalModule.js:639:11)
       at /usr/src/app/node_modules/webpack/lib/NormalModule.js:691:5
       at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:406:3
       at iterateNormalLoaders (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
       at iterateNormalLoaders (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:239:10)
       at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:254:3
       at runSyncOrAsync (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:143:11)
       at iterateNormalLoaders (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
   /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:146
   		if(isError) throw e;
   		            ^
   
   Error: error:0308010C:digital envelope routines::unsupported
       at new Hash (node:internal/crypto/hash:71:19)
       at Object.createHash (node:crypto:140:10)
       at BulkUpdateDecorator.hashFactory (/usr/src/app/node_modules/webpack/lib/util/createHash.js:138:18)
       at BulkUpdateDecorator.update (/usr/src/app/node_modules/webpack/lib/util/createHash.js:44:50)
       at RawSource.updateHash (/usr/src/app/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:64:8)
       at NormalModule._initBuildHash (/usr/src/app/node_modules/webpack/lib/NormalModule.js:752:17)
       at handleParseResult (/usr/src/app/node_modules/webpack/lib/NormalModule.js:816:10)
       at /usr/src/app/node_modules/webpack/lib/NormalModule.js:907:4
       at processResult (/usr/src/app/node_modules/webpack/lib/NormalModule.js:639:11)
       at /usr/src/app/node_modules/webpack/lib/NormalModule.js:691:5
       at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:406:3
       at iterateNormalLoaders (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
       at iterateNormalLoaders (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:239:10)
       at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:254:3
       at context.callback (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
       at makeSourceMapAndFinish (/usr/src/app/node_modules/ts-loader/dist/index.js:58:5) {
     opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
     library: 'digital envelope routines',
     reason: 'unsupported',
     code: 'ERR_OSSL_EVP_UNSUPPORTED'
   }
  ```

Not sure what needs to be changed/updated to make things work with an up-to-date version of `npm` and/or webpack; but it would be cool if you could have a look at this. :bow:

Disclaimer: I've created an "[Electron-wrapper](https://github.com/4ch1m/spritemate4electron)" for this cool app; and I'd like to update things on my end. :smile:

Thanks a lot!

**Comment by Esshahn** [comment]
Well first of all congrats on the electron build - how cool is that! I always wanrted to do it myself, but never got the time. Having said that, my time maintaining the project is pretty limited and I haven't even touched code for almost a year, saying I'm rusty would be an understatement.

Therefore I'm sorry to say that I'm probably not be able to fix the issue anytime soon. But by all means if you do find out what causes the issue, let me know. Cheers.

**Comment by 4ch1m** [comment]
All righty.
I've prepared a PR that will resolve these issues; making it possible to compile the app with up-to-date build-tools.
Would be cool if you could review/merge this any time soon.

And... btw... thanks for this cool sprite-editor! :smile:
